// Generated by phenopacket-tools/constants/create_classes.py. DO NOT EDIT!

use phenopackets::schema::v2::core::OntologyClass;

pub struct DiseaseStage;

impl DiseaseStage {
    pub fn stage_0() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C28051".to_string(),
            label: "Stage 0".to_string(),
        }
    }

    pub fn stage_i() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C27966".to_string(),
            label: "Stage I".to_string(),
        }
    }

    pub fn stage_ii() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C28054".to_string(),
            label: "Stage II".to_string(),
        }
    }

    pub fn stage_iii() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C27970".to_string(),
            label: "Stage III".to_string(),
        }
    }

    pub fn stage_iv() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C27971".to_string(),
            label: "Stage IV".to_string(),
        }
    }

    pub fn nyha_class_i() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C66904".to_string(),
            label: "New York Heart Association Class I".to_string(),
        }
    }

    pub fn nyha_class_ii() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C66905".to_string(),
            label: "New York Heart Association Class II".to_string(),
        }
    }

    pub fn nyha_class_iii() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C66907".to_string(),
            label: "New York Heart Association Class III".to_string(),
        }
    }

    pub fn nyha_class_iii_or_iv() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C7922".to_string(),
            label: "New York Heart Association Class III/IV".to_string(),
        }
    }

    pub fn nyha_class_iv() -> OntologyClass {
        OntologyClass {
            id: "NCIT:C66908".to_string(),
            label: "New York Heart Association Class IV".to_string(),
        }
    }
}



#[cfg(test)]
mod test {
    use super::*;
    use rstest::{fixture, rstest};


    #[rstest]

    fn test_stage_IV() {
        let stage4 = DiseaseStage::nyha_class_iv();
        let ncit_id = "NCIT:C66908";
        let ncit_label = "New York Heart Association Class IV"; 
        assert_eq!(ncit_id, stage4.id);
        assert_eq!(ncit_label, stage4.label);
    }



  

}